import {readFileSync} from 'node:fs';
import {createRequire} from 'node:module';
import {pathToFileURL} from 'node:url';
import test from 'node:test';
import assert from 'node:assert/strict';
const require=createRequire(`${process.env.PGLITE_TEST_ROOT||process.cwd()}/package.json`);
const {Window}=await import(pathToFileURL(require.resolve('happy-dom')).href);
const source=f=>readFileSync(new URL('../'+f,import.meta.url),'utf8');
const wait=()=>new Promise(r=>setTimeout(r,20));
test('member visit replaces the owner card, uses only public fields and skips private overview/rank loaders',async t=>{
 const w=new Window({url:'https://olafshop.com/profile.html#user/PlayerOne'});t.after(()=>w.happyDOM.close());
 w.document.body.innerHTML='<section id="panel-overview"><div id="profile-rank-root"></div><div id="profile-overview-root"></div></section>';
 w.OlafStore={currentUser:()=>({id:'my-private-id'})};
 const calls=[];w.olafSupabase={rpc:async(name,args)=>{calls.push(name);assert.equal(args.p_username,'PlayerOne');return {data:{displayName:'PlayerOne',bio:'<script>unsafe</script>',rank:2,avatar:'iconprofile/a.gif',games:[],email:'PRIVATE',balance:12345}};}};
 w.OlafOrders={fetchMyOrders:()=>assert.fail('must not fetch orders'),fetchPointBalance:()=>assert.fail('must not fetch balance')};
 for(const f of ['profile-member-route.js','profile-overview.js','profile-rank.js','profile-member.js'])w.eval(source(f));
 w.document.dispatchEvent(new w.Event('DOMContentLoaded'));await wait();
 assert.equal(w.document.documentElement.dataset.profileVisitor,'true');assert(calls.every(n=>n==='shop_member_profile'));
 assert(w.document.querySelector('.member-visitor-showcase h2').textContent.includes('PlayerOne'));
 assert.equal(w.document.querySelectorAll('.rank-emblem').length,6);
 assert(!w.document.querySelector('.member-customize,[data-rank-display],script'));
 assert.equal(w.document.querySelector('[data-visited-point-balance]').textContent,'—','old SQL never misrepresents a missing balance as zero');
 assert(!w.document.body.textContent.includes('PRIVATE'));assert(!w.document.body.textContent.includes('12345'));
 const nav=source('site-navigation.js');w.eval(nav.slice(0,nav.indexOf('  const ORDER_DESTINATION'))+'})();');
 w.OlafRankBadge.update({show:true,rank:6});assert.equal(w.document.querySelectorAll('[data-member-rank]').length,0,'own badge never overwrites visited member');
});
test('own #user route stays editable and old share controls are no longer mounted',async t=>{
 const w=new Window({url:'https://olafshop.com/profile.html#user'});t.after(()=>w.happyDOM.close());
 w.eval(source('profile-member-route.js'));assert.equal(w.OlafProfileRoute.visiting,false);
 const html=source('profile.html');assert(!html.includes('src="profile-sharing.js'));assert(!html.includes('href="profile-sharing.css'));
 assert(html.includes("if(panelName==='user')panelName='overview'"));
 assert(html.includes("if(window.OlafProfileRoute?.visiting)return;"));
});
test('visitor sidebar belongs to the signed-in viewer while stats and 0–12 games belong to the visited member',async t=>{
 const html=source('profile.html'),sidebar=html.match(/<aside class="profile-sidebar">[\s\S]*?<\/aside>/)[0];
 const w=new Window({url:'https://olafshop.com/profile.html#user/Other'});t.after(()=>w.happyDOM.close());
 w.document.body.innerHTML=sidebar+'<section id="panel-overview"><div id="profile-overview-root"></div></section>';
 let logoutCalled=false;
 w.OlafStore={ready:Promise.resolve(),currentUser:()=>({id:'viewer',displayName:'My Account',email:'my@example.com',role:'admin'}),logout:async()=>{logoutCalled=true;throw new Error('test failure');}};
 let ownBalanceCalls=0;w.OlafOrders={fetchPointBalance:async()=>{ownBalanceCalls++;return {balance:777};},fetchMyOrders:()=>assert.fail('no order details needed')};
 w.olafSupabase={rpc:async(name,args)=>{assert.equal(name,'shop_member_profile');assert.equal(args.p_username,'Other');return {data:{displayName:'Other',rank:0,games:Array.from({length:14},(_,i)=>({id:String(i),name:'Chosen '+i})),stats:{purchasedGames:111,pointBalance:27453,shopPoints:79500},email:'other-private@example.com'}};}};
 w.eval(source('profile-member-route.js'));w.eval(source('profile-member.js'));w.document.dispatchEvent(new w.Event('DOMContentLoaded'));await wait();
 assert.equal(w.document.querySelector('#profile-sidebar-name').textContent,'My Account');
 assert.equal(w.document.querySelector('#profile-sidebar-email').textContent,'my@example.com');
 assert.equal(w.document.querySelector('#profile-sidebar-point-balance').textContent,'777');assert(ownBalanceCalls>0);
 assert.equal(w.document.querySelector('[data-visited-game-count]').textContent,'111');
 assert.equal(w.document.querySelector('[data-visited-point-balance]').textContent,'27,453');
 assert.equal(w.document.querySelector('[data-visited-shop-points]').textContent,'79,500');
 assert.equal(w.document.querySelectorAll('.member-game-grid a').length,12);
 assert(!w.document.querySelector('#profile-overview-root').textContent.includes('my@example.com'));
 assert(!w.document.body.textContent.includes('other-private@example.com'));
 w.document.querySelector('#logout-btn').click();await wait();assert(logoutCalled);assert.equal(w.document.querySelector('#logout-btn').disabled,false);
 w.document.querySelector('[data-panel="orders"]').click();assert.equal(w.location.hash,'#orders');
});
test('guest sidebar requests login without fake viewer balances',async t=>{
 const w=new Window({url:'https://olafshop.com/profile.html#user/Other'});t.after(()=>w.happyDOM.close());
 w.document.body.innerHTML='<aside class="profile-sidebar"></aside><section id="panel-overview"><div id="profile-overview-root"></div></section>';
 w.OlafStore={currentUser:()=>null};w.olafSupabase={rpc:async()=>({data:null})};
 w.eval(source('profile-member-route.js'));w.eval(source('profile-member.js'));w.document.dispatchEvent(new w.Event('DOMContentLoaded'));await wait();
 assert(w.document.querySelector('.profile-sidebar a').href.endsWith('login.html'));
 assert(!w.document.querySelector('#profile-point-balance'));
});
test('friends menu hides search until Add friend; public-key search ignores stale results',async t=>{
 const w=new Window({url:'https://olafshop.com/profile.html#user'});t.after(()=>w.happyDOM.close());
 w.document.body.innerHTML='<div id="profile-overview-root"></div>';
 const pending=[];w.olafSupabase={rpc:(name,args)=>{assert.equal(name,'shop_search_members');return new Promise(resolve=>pending.push({args,resolve}));}};
 w.OlafStore={currentUser:()=>null};w.eval(source('friends.js'));
 w.eval(source('profile-member.js'));w.document.dispatchEvent(new w.Event('DOMContentLoaded'));await wait();w.dispatchEvent(new w.CustomEvent('olaf-profile-ready'));
 const menu=w.document.querySelector('.member-visit-nav'),page=w.document.getElementById('member-friends-page');
 assert.equal(menu.querySelector('input'),null);assert(page.hidden);assert.equal(menu.querySelector('.member-admin-link'),null);
 menu.querySelector('[data-friends-menu]').click();assert(!page.hidden);assert(w.document.getElementById('profile-overview-root').hidden);
 const form=page.querySelector('form'),input=form.elements.username;assert(form.hidden);
 page.querySelector('[data-add-friend]').click();assert(!form.hidden);
 input.value='โอลาฟ';form.dispatchEvent(new w.Event('submit',{cancelable:true}));assert.equal(pending[0].args.p_query,'โอลาฟ');
 pending[0].resolve({data:[{username:'one',nickname:'โอลาฟ',profileKey:'~public-key'},{username:'two',nickname:'<img onerror=alert(1)>'}]});await wait();
 assert.equal(form.querySelectorAll('.friends-search-results a').length,2);
 assert.equal(form.querySelector('.friends-search-results a').href,'https://olafshop.com/profile.html#user/~public-key');
 assert(form.querySelector('.friends-search-results').textContent.includes('@two'));assert(!form.querySelector('[onerror]'));
 input.value='older';input.dispatchEvent(new w.Event('input'));form.dispatchEvent(new w.Event('submit',{cancelable:true}));
 input.value='newer';input.dispatchEvent(new w.Event('input'));form.dispatchEvent(new w.Event('submit',{cancelable:true}));
 pending[2].resolve({data:[]});await wait();pending[1].resolve({data:[{username:'stale',nickname:'STALE'}]});await wait();
 assert(form.querySelector('.friends-search-results').textContent.includes('ไม่พบสมาชิก'));assert(!form.textContent.includes('STALE'));
 menu.querySelector('[data-friends-menu]').click();assert(page.hidden);assert(!w.document.getElementById('profile-overview-root').hidden);
});
