import test from 'node:test';
import assert from 'node:assert/strict';
import {createRequire} from 'node:module';
import {readFileSync} from 'node:fs';
const require=createRequire(`${process.env.PGLITE_TEST_ROOT || process.cwd()}/package.json`);
const {PGlite}=require('@electric-sql/pglite');
test('supplier permissions, atomic import and legacy preservation (PostgreSQL)',async()=>{
 const db=new PGlite();
 try{
 await db.exec(`create role anon; create role authenticated; create role service_role;
 create schema auth;
 create function auth.uid() returns uuid language sql as $$select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid$$;
 create function auth.role() returns text language sql as $$select current_setting('request.jwt.claim.role',true)$$;
 grant usage on schema auth to anon,authenticated,service_role;
 create table profiles(id uuid primary key,role text,status text);
 insert into profiles values ('11111111-1111-4111-8111-111111111111','admin','active'),('22222222-2222-4222-8222-222222222222','customer','active');
 grant select,update,insert on profiles to authenticated;
 create table products(id int,price int,stock int); insert into products values(1,99,5);`);
 await db.exec(readFileSync(new URL('../supabase-supplier-access.sql',import.meta.url),'utf8'));
 const role=async(r,id='')=>{await db.exec('reset role');await db.query("select set_config('request.jwt.claim.role',$1,false),set_config('request.jwt.claim.sub',$2,false)",[r,id]);await db.exec(`set role ${r}`);};
 const row={supplier:'499k',supplier_product_id:'10',product_type:'offline',name:'Test',stock:2,price:10,full_price:null,denuvo:false,steam:{description:'<p>HTML</p>'},image:'https://example.com/game.jpg'};
 const imp=rows=>db.query('select server_import_499k_offline($1::jsonb) as result',[JSON.stringify(rows)]);
 await role('service_role');
 assert.equal((await imp([row])).rows[0].result.inserted,1);
 assert.equal((await imp([row])).rows[0].result.updated,1);
 const id=(await db.query('select id from supplier_products')).rows[0].id;
 await assert.rejects(imp([{...row,supplier_product_id:'11'},{...row,supplier_product_id:'12',price:-1}]));
 assert.equal((await db.query('select count(*)::int as n from supplier_products')).rows[0].n,1);
 await role('authenticated','22222222-2222-4222-8222-222222222222');
 assert.equal((await db.query('select * from supplier_products')).rows.length,0);
 await assert.rejects(db.exec("update profiles set role='admin' where id=auth.uid()"));
 await assert.rejects(db.query('select admin_update_supplier_product($1,$2)',[id,'{"selling_price":20}']));
 await assert.rejects(imp([row]));
 await assert.rejects(db.exec('select * from supplier_product_secrets'));
 await role('authenticated','11111111-1111-4111-8111-111111111111');
 assert.equal((await db.query('select price from supplier_products')).rows.length,1);
 await assert.rejects(db.exec('update supplier_products set price=0'));
 await assert.rejects(db.query('select admin_update_supplier_product($1,$2)',[id,'{"price":0}']));
 await db.query('select admin_update_supplier_product($1,$2)',[id,'{"selling_price":30,"is_visible":true,"status":"active","admin_note":"Keep"}']);
 await assert.rejects(db.exec('select * from supplier_product_secrets'));
 await role('anon');
 await assert.rejects(db.exec('select * from supplier_products'));
 const visible=(await db.query('select * from supplier_public_products')).rows[0];
 assert.equal(visible.title,'Test');assert.equal(visible.available,true);
 assert(!('price' in visible));assert(!('steam' in visible));assert(!('supplier_product_id' in visible));
 await role('service_role');await imp([{...row,price:15,stock:0}]);
 const saved=(await db.query('select * from supplier_products')).rows[0];
 assert.equal(Number(saved.selling_price),30);assert.equal(saved.admin_note,'Keep');assert.equal(saved.denuvo,false);assert.equal(saved.full_price,null);assert.equal(saved.steam.description,'<p>HTML</p>');
 await db.query('insert into supplier_product_secrets(supplier_product_id,ciphertext,encryption_key_version) values($1,$2,$3)',[id,new Uint8Array([1,2,3]),'test']);
 assert.equal((await db.query('select * from supplier_product_secrets')).rows.length,1);
 await db.exec('reset role');assert.deepEqual((await db.query('select * from products')).rows,[{id:1,price:99,stock:5}]);
 }finally{await db.close();}
});
